version: "3.9"
services:
  socket-server:
    build:
      context: ./infrastructure/socket
      dockerfile: Dockerfile
    image: socket-server
    container_name: socket-server
    restart: always
    volumes:
      - ./:/var/www/html
      - ./infrastructure/socket/site.conf:/etc/apache2/conf.d/default.conf
      - ./infrastructure/socket/httpd.conf:/etc/apache2/httpd.conf
      - ./infrastructure/socket/supervisord.ini:/etc/supervisor.d/supervisord-custom.ini
      - ./infrastructure/socket/custom-php.ini:/etc/php83/conf.d/01_custom-php.ini
    ports:
      - 8083:80
      - 8080:8080
    depends_on:
      - socket-cache

  socket-cache:
    restart: always
    image: eqalpha/keydb
    container_name: socket-cache
    volumes:
      - socket_cache:/data
      - ./infrastructure/cache/keydb.conf:/etc/keydb/keydb.conf:ro
      - ./infrastructure/cache/sysctl.conf:/etc/sysctl.conf:ro
volumes:
  socket_cache:
    driver: local
